# Project information
site_name: Bowling's TechStack
site_url: http://note.bowling233.top
repo_url: https://github.com/Tiandians/TechStack
repo_name: TechStack
edit_uri: blob/master/docs/
site_description: è¿™æ˜¯ Bowling çš„ç¬”è®°æœ¬
site_author: Bowling
copyright: <a href="https://beian.miit.gov.cn/" target="_blank">æµ™ICPå¤‡2022036274å·-1</a>

# Material
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

extra:
  social:
    - icon: material/home-circle
      link: http://bowling233.com
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
  - stylesheets/flink.css

#Documentation layout

# Build directories
theme:
  name: material
  logo: assets/bowling.svg
  favicon: assets/bowling.svg
  features:
    - search.highlight
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - tags:
      tags_file: Tags.md
  - search:

# Navigation
nav:
  - ğŸ é¦–é¡µ: # /
      - ğŸ¡é¦–é¡µ: index.md
      - ğŸ“é¡¹ç›®: Project.md
      - ğŸ”–æ ‡ç­¾: Tags.md
      - ğŸ”—é“¾æ¥: Links.md
      - âš ï¸æµ‹è¯•: Test.md
  - ğŸ”¨åŸºç¡€æŠ€èƒ½: # basic/
      - ğŸ§±åŸºç¡€: basic/Basic.md
      - ğŸ§Linux: basic/Linux.md
      - ğŸ˜VSCode: basic/VSCode.md
      - ğŸ¥³gcc: basic/gcc.md
      - ğŸ˜¼Git: basic/Git.md
      - ğŸ¹å¿«æ·é”®æ±‡æ€»: basic/Shortcuts.md
      - âœï¸å†™ä½œ: # basic/writing/
        - basic/writing/Copywriting.md
        - basic/writing/Vim.md
        - basic/writing/Markdown.md
        - basic/writing/Latex.md
      - â–¶ï¸ç§‘æ™®è§†é¢‘: basic/Videos.md
  - ğŸæ•™ç¨‹å’Œè®°å½•: # misc/
    - ğŸ§Linux:
      - linux/LinuxProblemSolver.md
      - misc/Ubuntu.md
    - misc/QA.md
    - misc/UbuntuSetupRecord.md
    - misc/RemoteDesk.md
    - misc/PhoneSetupRecord.md
    - misc/SyncthingConf.md
  - âš”ï¸è¯­è¨€: # language/
      - ğŸ¹C: # language/c/
        - language/c/CBasic.md
        - language/c/IO.md
        - language/c/Memory.md
        - language/c/CPuzzle.md
        - language/c/CSTL.md
      - ğŸ§°C++: # language/cpp/
        - language/cpp/CppBasic.md
  - ğŸ§®è®¡ç®—æœºç³»ç»Ÿ: # operatesystem/
      - system/discrete.md
      - CSAPP: 
        - system/csapp/index.md
        - system/csapp/Lecture/Lecture1.md
        - system/csapp/Lab/L0.md
        - system/csapp/Lab/BC1.md
        - ä¹¦æœ¬:
          - system/csapp/Book/Chapter1.md
          - system/csapp/Book/Chapter2.md
          - system/csapp/Book/Chapter3.md
  - ğŸŒWebDev: # webdev/
      - ğŸ“„ç½‘é¡µå¼€å‘: # webdev/webpage/
        - webdev/webpage/HTMLBasic.md
        - webdev/webpage/HTMLAdvanced.md
        - webdev/webpage/CSSBasic.md
        - webdev/webpage/CSSAdvanced.md
        - webdev/webpage/JavaScriptBasic.md
        - webdev/webpage/ReactBasic.md
      - ğŸ–¥WebæœåŠ¡å™¨: # webdev/webserver/
        - webdev/webserver/Protocol.md
        - webdev/webserver/HTTP.md
        - ç¯å¢ƒåŠå…¶é…ç½®:
            - webdev/webserver/Docker.md
            - webdev/webserver/PHP.md
        - webdev/webserver/NginxBasic.md
      - ğŸ’»Blogæ­å»º:
        - webdev/webserver/Domain_and_DNS.md
        - webdev/webserver/Proxy.md
  - ğŸ¤”æ€è€ƒ: # think/
      - think/MobileOffice.md
  - ğŸ“šå›¾ä¹¦é¦†: # books/
      - books/Foundations_Of_Computer_Science.md
      - books/è®¡ç®—æœºç»„æˆä¸è®¾è®¡_ç¡¬ä»¶è½¯ä»¶æ¥å£.md
      - books/é‡å­è®¡ç®—å…¥é—¨.md
  - ğŸ«è¯¾ç¨‹ç¬”è®°: # course/
      - course/Course.md
      - course/GeneralPhysics.md
      - course/Nand2Tetris.md
      - course/Analysis2.md
      - é«˜ç­‰ä»£æ•°:
        - course/Algebra/index.md
        - course/Algebra/Chapter1.md
        - course/Algebra/Chapter2.md