# Project information
site_name: Bowling's TechStack
site_url: http://note.bowling233.top
repo_url: https://github.com/Tiandians/TechStack
repo_name: TechStack
edit_uri: blob/master/docs/
site_description: è¿™æ˜¯ Bowling çš„ç¬”è®°æœ¬
site_author: Bowling
copyright: <a href="https://beian.miit.gov.cn/" target="_blank">æµ™ICPå¤‡2022036274å·-1</a>

# Material
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

extra:
  social:
    - icon: material/home-circle
      link: http://bowling233.com
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css

#Documentation layout

# Build directories
theme:
  name: material
  logo: assets/bowling.svg
  favicon: assets/bowling.svg
  features:
    - search.highlight
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - tags:
      tags_file: Tags.md
  - search:

# Navigation
nav:
  - ğŸ é¦–é¡µ: # /
      - ğŸ¡é¦–é¡µ: "README.md"
      - ğŸ“é¡¹ç›®: "Project.md"
      - ğŸ”–æ ‡ç­¾: "Tags.md"
      - ğŸ”—é“¾æ¥: "Links.md"
      - âš ï¸æµ‹è¯•: "Test.md"
      - â˜£ï¸æ‚é¡¹: "Misc.md"
  - ğŸ”¨åŸºç¡€æŠ€èƒ½: # basic/
      - ğŸ§±åŸºç¡€: "basic/Basic.md"
      - âœï¸å†™ä½œ: # basic/writing/
        - "basic/writing/Copywriting.md"
        - "basic/writing/VSCode.md"
        - "basic/writing/Vim.md"
        - "basic/writing/Markdown.md"
        - "basic/writing/Latex.md"
      - â–¶ï¸ç§‘æ™®è§†é¢‘: "basic/Videos.md"
      - ğŸ§Linux: # basic/linux/
        - "basic/linux/LinuxBasic.md"
        - "basic/linux/LinuxUtility.md"
        - Tools: # basic/linux/tools
            - "basic/linux/tools/gcc.md"
            - "basic/linux/tools/ssh.md"
        - "basic/linux/LinuxUsers.md"
        - "basic/linux/LinuxFileSystem.md"
        - "basic/linux/LinuxKernel.md"
      - ğŸ˜¼Git: # basic/git/
        - "basic/git/GitBasic.md"
        - "basic/git/GitPro.md"
      - âš™ï¸æ‚é¡¹: # basic/miscellaneous/
        - "basic/miscellaneous/Security.md"
        - "basic/miscellaneous/RegularExpression.md"
      - ğŸ”§é—®é¢˜å’Œè§£å†³: # basic/problem/
        - "basic/problem/QA2022.md"
        - "basic/problem/BlogSetupRecord.md"
        - "basic/problem/UbuntuSetupRecord.md"
  - ğŸŒWebDev: # webdev/
      - ğŸ“„ç½‘é¡µå¼€å‘: # webdev/webpage/
        - "webdev/webpage/HTMLBasic.md"
        - "webdev/webpage/HTMLAdvanced.md"
        - "webdev/webpage/CSSBasic.md"
        - "webdev/webpage/CSSAdvanced.md"
        - "webdev/webpage/JavaScriptBasic.md"
        - "webdev/webpage/JavaScriptAdvanced.md"
        - "webdev/webpage/ReactBasic.md"
        - "webdev/webpage/ReactAdvanced.md"
      - ğŸ–¥WebæœåŠ¡å™¨: # webdev/webserver/
        - "webdev/webserver/Protocol.md"
        - "webdev/webserver/HTTP.md"
        - "webdev/webserver/LinuxServer.md"
        - ç¯å¢ƒåŠå…¶é…ç½®:
            - "webdev/webserver/Docker.md"
            - "webdev/webserver/PHP.md"
        - "webdev/webserver/NginxBasic.md"
      - ğŸ’»Blogæ­å»º:
        - "webdev/webserver/Domain_and_DNS.md"
        - "webdev/webserver/Proxy.md"
        - "webdev/webserver/GitHubPages.md"
  - âš”ï¸ç¼–ç¨‹è¯­è¨€: # program/
      - ğŸ¹C: # program/c/
        - "program/c/CBasic.md"
        - "program/c/CPuzzle.md"
        - "program/c/CSTL.md"
        - "program/c/CTricks.md"
      - ğŸ§°C++: # program/cpp/
        - "program/cpp/CppBasic.md"
        - "program/cpp/CppAdvanced.md"
        - "program/cpp/CppSTL.md"
      - ğŸ”«Python: # program/python/
        - "program/python/PythonBasic.md"
      - ğŸ§¨Java: # program/java
        - "program/java/JavaBasic.md"
  - ğŸ§®æ“ä½œç³»ç»Ÿ: # operatesystem/
      - "operatesystem/MemoryHierarchy.md"
      - "operatesystem/VirtualMemory.md"
  - ğŸ’½ç¡¬ä»¶: # hardware/
      - "hardware/LogicCircuit.md"
      - "hardware/MOSFET.md"
      - "hardware/Storage.md"
  - ğŸ¤”æ€è€ƒ: # think/
      - "think/MobileOffice.md"
  - ğŸ“šå›¾ä¹¦é¦†: # books/
      - "books/è®¡ç®—æœºç§‘å­¦å¯¼è®º.md"
      - "books/è®¡ç®—æœºç»„æˆä¸è®¾è®¡_ç¡¬ä»¶è½¯ä»¶æ¥å£.md"
      - "books/é‡å­è®¡ç®—å…¥é—¨.md"
      - "books/æ·±å…¥ç†è§£è®¡ç®—æœºç³»ç»Ÿ.md"
  - ğŸ«è¯¾ç¨‹ç¬”è®°: # course/
      - "course/Course.md"
      - ğŸ§ªæ™®é€šåŒ–å­¦ï¼ˆHï¼‰:
        - "course/æ™®é€šåŒ–å­¦/æ™®é€šåŒ–å­¦H.md"
        - "course/æ™®é€šåŒ–å­¦/åŒ–å­¦çƒ­åŠ›å­¦.md"
        - "course/æ™®é€šåŒ–å­¦/åŒ–å­¦åŠ¨åŠ›å­¦åŸºç¡€.md"
        - "course/æ™®é€šåŒ–å­¦/ç”µåŒ–å­¦åŸºç¡€.md"
